# Generated by Django 3.2.25 on 2025-10-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True)),
                ('last_name', models.TextField(blank=True)),
                ('address_street_number', models.IntegerField(blank=True)),
                ('address_street_name', models.TextField(blank=True)),
                ('address_apartment_number', models.IntegerField(blank=True)),
                ('address_zip_code', models.IntegerField(blank=True)),
                ('date_birth', models.DateField(blank=True)),
                ('date_registration', models.DateField(blank=True)),
                ('party', models.CharField(blank=True, max_length=2)),
                ('precinct_number', models.IntegerField(blank=True)),
                ('v20state', models.BooleanField(blank=True)),
                ('v21town', models.BooleanField(blank=True)),
                ('v21primary', models.BooleanField(blank=True)),
                ('v22general', models.BooleanField(blank=True)),
                ('v23town', models.BooleanField(blank=True)),
                ('voter_score', models.IntegerField(default=0)),
            ],
        ),
    ]
