# Generated by Django 3.2.25 on 2025-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_ulr',
            field=models.URLField(blank=True),
        ),
    ]
