# Generated by Django 3.2.25 on 2025-09-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_article_image_ulr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True)),
                ('display_name', models.TextField(blank=True)),
                ('bio_text', models.TextField(blank=True)),
                ('join_date', models.TextField(blank=True)),
                ('profile_image_url', models.URLField(blank=True)),
            ],
        ),
    ]
