# Generated by Django 3.2.25 on 2025-09-30 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_alter_profile_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('bio_text', models.TextField()),
                ('published', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mini_insta.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
