# Generated by Django 3.2.25 on 2025-09-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0006_auto_20250930_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='text',
        ),
    ]
