# Generated by Django 3.2.25 on 2025-09-30 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0007_auto_20250930_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='profile',
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_insta.post'),
        ),
    ]
