# Generated by Django 3.2.25 on 2025-10-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0010_photo_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
